# Site settings
title: Poconos Resort Pennsylvania | Split Rock Resort
email: info@splitrockresort.com
description: > # Our four-season Poconos resort in Pennsylvania, Split Rock Resort, sits on the 125-acre Lake Harmony, surrounded by the quiet, rolling hills of Eastern PA..
baseurl: ""
url: "http://www.splitrockresort.com/" # the base hostname & protocol for your site
permalink: pretty

default_lang: 'en'
languages: ['en']


# Build settings
markdown: kramdown

port: 8080

default_lang: 'en'
languages: ['en']

exclude:
  - 'sitemap.json'
  - 'assets'
  
keep_files: ['assets']
rsync_copy: ['_assets']
  